#!/bin/bash

# set timezone
if [ -z "$TIMEZONE" ]; then
    export TIMEZONE='UTC'
fi
cat /usr/share/zoneinfo/$TIMEZONE > /etc/localtime
echo $TIMEZONE > /etc/timezone

# run init scripts
run-parts /etc/init.d

# switch to non-root user
su ${USER} -c "$@"